### ISSUE TITLE
Page Won't Show!

### ISSUE THREAD

**Issue by arch-master** [amercier/badge-generator#126]
I tried loading your site in the latest versions of Chrome, Firefox, and Safari. On all three browsers, the title, favicon, and page background showed, but nothing else. I really want to use your website! Does it work for you? Screenshot of console:
![screenshot](https://cloud.githubusercontent.com/assets/25555850/25071326/52f6ba8c-22b4-11e7-90d0-49fcfe99b8c9.jpg)

**Comment by amercier** [comment]
Fixed, sorry for the long, long delay.
