### ISSUE TITLE
Add org mode format in addition to markdown for badges

### ISSUE THREAD

**Issue by gabesoft** [amercier/badge-generator#2]

**Comment by amercier** [comment]
@gabesoft Could you provide any link, documentation, example, please?

**Comment by gabesoft** [comment]
Here's an example 
`[[http://melpa.org/#/evil-mc][file:http://melpa.org/packages/evil-mc-badge.svg?style=flat-square]]`
You can see it in action here https://raw.githubusercontent.com/gabesoft/evil-mc/master/README.org
Here's some documentation on how to display links in org mode http://orgmode.org/guide/External-links.html#External-links
